[program:smart-perkemi-email-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/Users/macbookair/Documents/website/smart-perkemi/smart-perkemi-v2
command=/opt/homebrew/bin/php artisan queue:work redis --queue=emails --sleep=3 --tries=3 --timeout=60 --max-time=3600
autostart=true
autorestart=true
startsecs=1
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=120
user=macbookair
numprocs=1
redirect_stderr=true
stdout_logfile=/Users/macbookair/Documents/website/smart-perkemi/smart-perkemi-v2/storage/logs/worker-emails.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
